from .computador import ComputadorSerializer
from .notebook import NotebookSerializer
from .ordemservico import OrdemServicoSerializer, OrdemServicoReadSerializer, UsuarioDetalheOrdermServicoSerializer
