# Generated by Django 4.2.5 on 2023-09-27 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
        ('inforratica', '0002_remove_computador_imagem_computador_capa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notebook',
            name='imagem',
        ),
        migrations.AddField(
            model_name='notebook',
            name='capa',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='uploader.image'),
        ),
    ]
