# Generated by Django 4.2.6 on 2023-10-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inforratica", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordemservico",
            name="status",
            field=models.TextField(default=None, max_length=50, null=True),
        ),
    ]
