# Generated by Django 4.2.1 on 2023-05-26 18:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inforratica", "0003_alter_computer_imagem"),
    ]

    operations = [
        migrations.RenameField(
            model_name="computer",
            old_name="fonte",
            new_name="cliente",
        ),
        migrations.RemoveField(
            model_name="computer",
            name="gabinete",
        ),
        migrations.RemoveField(
            model_name="computer",
            name="hd_ssd",
        ),
        migrations.RemoveField(
            model_name="computer",
            name="imagem",
        ),
        migrations.RemoveField(
            model_name="computer",
            name="memoria_ram",
        ),
        migrations.RemoveField(
            model_name="computer",
            name="placa_mae",
        ),
        migrations.RemoveField(
            model_name="computer",
            name="placa_video",
        ),
        migrations.RemoveField(
            model_name="computer",
            name="preco",
        ),
        migrations.RemoveField(
            model_name="computer",
            name="processador",
        ),
    ]
