# Generated by Django 4.2.6 on 2023-10-09 15:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inforratica", "0003_ordemservico_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ordemservico",
            old_name="usuario",
            new_name="cliente",
        ),
    ]
