# Generated by Django 4.2.6 on 2023-10-10 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inforratica", "0004_rename_usuario_ordemservico_cliente"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Cliente",
        ),
        migrations.AlterField(
            model_name="ordemservico",
            name="cliente",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ordensservico",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
