# Generated by Django 4.2.1 on 2023-05-26 18:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inforratica", "0004_rename_fonte_computer_cliente_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Computer",
        ),
    ]
