# Generated by Django 4.2.6 on 2023-10-10 17:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inforratica", "0005_delete_cliente_alter_ordemservico_cliente"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ordemservico",
            old_name="cliente",
            new_name="usuario",
        ),
    ]
