# Generated by Django 4.2.1 on 2023-05-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inforratica", "0006_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="computer",
            name="imagem",
            field=models.URLField(max_length=100),
        ),
    ]
