# Generated by Django 4.2.6 on 2023-10-13 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inforratica", "0006_rename_cliente_ordemservico_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordemservico",
            name="usuario",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ordensservico",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
