# Generated by Django 4.2.1 on 2023-05-26 18:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inforratica", "0007_alter_computer_imagem"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Computer",
        ),
    ]
