# Generated by Django 4.2.1 on 2023-05-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("inforratica", "0010_delete_computer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Computador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cliente", models.CharField(max_length=100)),
                ("placa_mae", models.CharField(max_length=100)),
                ("processador", models.CharField(max_length=100)),
                ("memoria_ram", models.CharField(max_length=100)),
                ("hd", models.CharField(max_length=100)),
                ("ssd", models.CharField(max_length=100)),
                ("fonte", models.CharField(max_length=100)),
                ("gabinete", models.CharField(max_length=100)),
                ("placa_de_video", models.CharField(max_length=100)),
                ("preco", models.CharField(max_length=100)),
                ("imagem", models.URLField(max_length=100)),
            ],
        ),
    ]
