# Generated by Django 4.2.3 on 2023-07-07 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inforratica', '0011_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computador',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='computador',
            name='preco',
        ),
        migrations.AlterField(
            model_name='computador',
            name='imagem',
            field=models.URLField(),
        ),
    ]
