# Generated by Django 4.2.3 on 2023-07-07 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inforratica', '0012_remove_computador_cliente_remove_computador_preco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computador',
            name='cooler',
            field=models.CharField(default='Stock', max_length=50),
        ),
        migrations.AlterField(
            model_name='computador',
            name='fonte',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='computador',
            name='gabinete',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='computador',
            name='hd',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='computador',
            name='memoria_ram',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='computador',
            name='placa_de_video',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='computador',
            name='placa_mae',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='computador',
            name='processador',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='computador',
            name='ssd',
            field=models.CharField(max_length=50),
        ),
    ]
