# Generated by Django 4.2.3 on 2023-07-08 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inforratica', '0013_computador_cooler_alter_computador_fonte_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=50)),
            ],
        ),
    ]
