# Generated by Django 4.2.4 on 2023-08-01 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inforratica', '0015_alter_cliente_options_computador_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computador',
            name='memoria_ram',
            field=models.CharField(max_length=80),
        ),
    ]
