# Generated by Django 4.2.4 on 2023-08-07 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inforratica', '0016_alter_computador_memoria_ram'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('descricao', models.TextField(max_length=500)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordensservico', to='inforratica.cliente')),
                ('computador', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordensservico', to='inforratica.computador')),
            ],
        ),
    ]
