# Generated by Django 4.2.4 on 2023-08-14 13:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inforratica', '0018_alter_ordemservico_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='senha',
            field=models.CharField(default='', max_length=30, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
